### PR TITLE
Assumed fix for the streams not flushing to disk.

### PR DESCRIPTION
**Pull request by jzohrab**
Trying to force a flush to the write stream for reports.

### CODE REVIEW

**Comment by ryanblock** [comment]
Hey! Why write this to disk at all? Once we have a completed buffer we can just write directly into s3.

**Comment by jzohrab** [comment]
Hi @ryanblock -- I've been battling with the reports for a while.  I originally did try to stream directly to s3 (see notes in https://github.com/covidatlas/li/issues/264) but was running into problems, so switched to disk.  I think I could probably switch back and write directly to s3, but I want to get everything working like this first.

**Comment by ryanblock** [comment]
Bear in mind you get a grand total of 512MB disk to work with in Lambda. Fwiw I’d personally try to avoid streams of any kind here and process sync, then write to S3.

**Comment by jzohrab** [comment]
Yes I know that, thanks. :-)  I'm doing this with what I know, and have had to try out different approaches as things worked or failed.  If there's a better way, please pass along a working code sample ... I've run into memory issues, timeouts, buffering/non-flushing, etc.  This doesn't seem like it would be tough, but I've been working at it for a few days now, and am not sure if it's stable or not.

**Pull request merged**
